 default: &default
   adapter: postgresql
   encoding: utf8
   pool: 5
   host: localhost
   username: postgres
   password: masterx

 development:
   <<: *default
   database: db/development_bulma

 test:
   <<: *default
   database: db/test_bulma
